// ===========================
// インポート: 必要な型と機能を読み込む
// ===========================

// Next.jsのメタデータ型定義（SEO設定用）
import type { Metadata } from "next";
// Google Fontsから2つのフォントファミリーを読み込む
// - Geist: サンセリフフォント（通常のテキスト用）
// - Geist_Mono: モノスペースフォント（コード表示用）
import { Geist, Geist_Mono } from "next/font/google";
// グローバルCSSファイルを読み込む（Tailwind CSSの設定など）
import "./globals.css";

// ===========================
// フォント設定: Google Fontsの設定
// ===========================

/**
 * Geistフォント（サンセリフ）の設定
 * - variable: CSS変数名を指定（--font-geist-sans）
 * - subsets: 読み込む文字セット（latinは英数字・記号）
 * 
 * この設定により、CSSで var(--font-geist-sans) として使用可能
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * Geist Monoフォント（モノスペース）の設定
 * - コードブロックや等幅フォントが必要な箇所で使用
 * - variable: CSS変数名を指定（--font-geist-mono）
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ===========================
// メタデータ: SEO設定（検索エンジン最適化）
// ===========================

/**
 * ページのメタデータ設定
 * - title: ブラウザのタブに表示されるタイトル
 * - description: 検索結果に表示される説明文
 * 
 * このメタデータは全ページで共通で使用されます
 * 個別ページで上書きすることも可能です
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ===========================
// ルートレイアウト: アプリケーション全体の枠組み
// ===========================

/**
 * RootLayoutコンポーネント
 * 
 * このコンポーネントはアプリケーション全体の「枠組み」を定義します
 * - すべてのページで共通のHTML構造を提供
 * - フォント設定を全ページに適用
 * - {children}の部分に各ページのコンテンツが挿入される
 * 
 * @param children - 各ページのコンテンツ（app/page.tsx など）
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;  // React要素（ページコンポーネント）
}>) {
  return (
    // HTML全体の構造を定義
    <html lang="ja">  {/* lang="ja": 日本語ページであることを宣言（アクセシビリティ対応） */}
      <body
        // テンプレートリテラル（``）で複数のクラス名を結合
        // - geistSans.variable: --font-geist-sans CSS変数を有効化
        // - geistMono.variable: --font-geist-mono CSS変数を有効化
        // - antialiased: フォントのアンチエイリアス（滑らか表示）を有効化
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ここに各ページのコンテンツが挿入される */}
        {/* 例: app/page.tsx の内容がここに表示される */}
        {children}
      </body>
    </html>
  );
}